name: sync

on:
  issue_comment:
    types:
      - created
      - deleted
      - edited
  issues:
    types:
      - closed
      - deleted
      - edited
      - labeled
      - opened
      - pinned
      - reopened
      - transferred
      - unlabeled
      - unpinned

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the default branch
        uses: actions/checkout@v3
      - name: Check out 'data' branch # dataブランチの内容を dataディレクトリに配置
        uses: actions/checkout@v3
        with:
          path: data # Relative path under $GITHUB_WORKSPACE to place the repository
          ref: data # The branch, tag or SHA to checkout
        continue-on-error: true
      - name: Generate issue files in "data/issues/{issue index}/"
        uses: r7kamura/gialog-sync@v1 # https://github.com/r7kamura/gialog-sync
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and push "data"
        uses: peaceiris/actions-gh-pages@v3 # https://github.com/peaceiris/actions-gh-pages
        with:
          destination_dir: .
          disable_nojekyll: true
          force_orphan: true # This allows you to make your publish branch with only the latest commit.
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: data
          publish_dir: data
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - run: npm install
      - run: npm run export
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
          #  The default of "publish_branch" is "gh-pages"
